### ISSUE TITLE
app in device automatically closes when using method MusicFiles.getAll

### ISSUE THREAD

**Issue by ShumGG** [cinder92/react-native-get-music-files#88]

**Comment by Drazail** [comment]
@ShumGG 

please share some logs ;)

**Comment by ajoykarmakar** [comment]
I have same issue, here is my log -

  ```
 2020-12-01 13:23:07.420 15358-18035/app.packagename.in E/AndroidRuntime: FATAL EXCEPTION: asyncTask
    Process: app.packagename.in, PID: 15358
    java.lang.IllegalArgumentException: Invalid column *
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:951)
        at android.content.ContentResolver.query(ContentResolver.java:887)
        at android.content.ContentResolver.query(ContentResolver.java:843)
        at com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule.getSongs(RNReactNativeGetMusicFilesModule.java:150)
        at com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule.access$000(RNReactNativeGetMusicFilesModule.java:37)
        at com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule$1.run(RNReactNativeGetMusicFilesModule.java:132)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by cinder92** [comment]
closing this due to not response
