### ISSUE TITLE
App getting crashed

### ISSUE THREAD

**Issue by ajoykarmakar** [cinder92/react-native-get-music-files#90]
Here is my log -

  ```
 2020-12-01 13:23:07.420 15358-18035/app.packagename.in E/AndroidRuntime: FATAL EXCEPTION: asyncTask
    Process: app.packagename.in, PID: 15358
    java.lang.IllegalArgumentException: Invalid column *
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:951)
        at android.content.ContentResolver.query(ContentResolver.java:887)
        at android.content.ContentResolver.query(ContentResolver.java:843)
        at com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule.getSongs(RNReactNativeGetMusicFilesModule.java:150)
        at com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule.access$000(RNReactNativeGetMusicFilesModule.java:37)
        at com.cinder92.musicfiles.RNReactNativeGetMusicFilesModule$1.run(RNReactNativeGetMusicFilesModule.java:132)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by CuiBenyong** [comment]
same issue, any idea?

**Comment by uit2712** [comment]
I found a solution for this: go to file 'android/src/main/java/com/cinder92/musicfiles/RNReactNativeGetMusicFilesModule.java'. Then
Change
Cursor musicCursor = musicResolver.query(musicUri, STAR, selection, null, sortOrder);
To
Cursor musicCursor = musicResolver.query(musicUri, null, selection, null, sortOrder);

**Comment by 13627491210** [comment]
> I found a solution for this: go to file 'android/src/main/java/com/cinder92/musicfiles/RNReactNativeGetMusicFilesModule.java'. Then Change Cursor musicCursor = musicResolver.query(musicUri, STAR, selection, null, sortOrder); To Cursor musicCursor = musicResolver.query(musicUri, null, selection, null, sortOrder);

It works for me, thanks

**Comment by CollinsRollinsDev** [comment]
> I found a solution for this: go to file 'android/src/main/java/com/cinder92/musicfiles/RNReactNativeGetMusicFilesModule.java'. Then
> Change
> Cursor musicCursor = musicResolver.query(musicUri, STAR, selection, null, sortOrder);
> To
> Cursor musicCursor = musicResolver.query(musicUri, null, selection, null, sortOrder);

Wow!! this is what works for me! Thanks a lot for this.

**Comment by cinder92** [comment]
closing this in favor of https://github.com/cinder92/react-native-get-music-files/pull/108
